### ISSUE TITLE
Expected u.is_cuda() to be true, but got false.

### ISSUE THREAD

**Issue by darkmingy** [MzeroMiko/VMamba#43]
Hello! I try to run VMamba on Ubuntu, but I received such error:
File "/VMamba-main/classification/models/vmamba.py", line 150, in forward
    out, x, *rest = selective_scan_cuda_core.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows)
RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
Then I put data and model in GPU.
And I received such error:
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
The cuda version I downloaded matches the pytorch version. I'm a freshman to learn Mamba, what should I do to solve this problem?

**Comment by MzeroMiko** [comment]
Can you run the code with `CUDA_LAUNCH_BLOCKING=1` and show the context around the error message? 
Also you can your environment with `nvcc -V`, `python -VV`, `pip -V`, `conda list`, `pip list` .

**Comment by darkmingy** [comment]
I redownloaded pytorch and found that any version of torch >= 2.0.0 would have problems.
I was able to get it to work by pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117. And update selective_scan_cuda_core after downloading the new version of the torch. I've solved the problem. Thanks!

**Comment by Caughyhzd** [comment]
> 我重新下载了pytorch，发现torch>=2.0.0的任何版本都会有问题。我能够通过 pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url [https://download.pytorch.org/](https://download.pytorch.org/whl/cu117) 让它工作[whl/cu117](https://download.pytorch.org/whl/cu117)。并在下载新版本的torch后更新selective_scan_cuda_core。我已经解决了这个问题。谢谢！

Hello, can you provide a specific explanation? I have also encountered this issue recently

**Comment by VagoLapis** [comment]
> I redownloaded pytorch and found that any version of torch >= 2.0.0 would have problems. I was able to get it to work by pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117. And update selective_scan_cuda_core after downloading the new version of the torch. I've solved the problem. Thanks!

你好，我想问下你可以跑通代码吗，我在使用低于2.0版本的CUDA时，会出现mamba-ssm库无法使用的问题。
Hello, I would like to ask if you can run through the code. When I use CUDA version lower than 2.0, there will be a problem that mamba-ssm library cannot be used.

**Comment by darkmingy** [comment]
> > I redownloaded pytorch and found that any version of torch >= 2.0.0 would have problems. I was able to get it to work by pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117. And update selective_scan_cuda_core after downloading the new version of the torch. I've solved the problem. Thanks!
> 
> 你好，我想问下你可以跑通代码吗，我在使用低于2.0版本的CUDA时，会出现mamba-ssm库无法使用的问题。 Hello, I would like to ask if you can run through the code. When I use CUDA version lower than 2.0, there will be a problem that mamba-ssm library cannot be used.

我可以跑通。可以参考看看：https://blog.csdn.net/aaatomaaa/article/details/135759438

**Comment by NicoleRR2001** [comment]
I want to ask how to upgrade selective_scan_cuda

**Comment by NicoleRR2001** [comment]
> I redownloaded pytorch and found that any version of torch >= 2.0.0 would have problems. I was able to get it to work by pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117. And update selective_scan_cuda_core after downloading the new version of the torch. I've solved the problem. Thanks!

I want to ask how to update selective_scan_cuda_core,just run it again?or do I need to change some code? thank you

**Comment by ghost-baigao** [comment]
File "/home/LYH/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 42, in forward
    out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)
RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
请问，怎么解决这个问题呀

**Comment by NicoleRR2001** [comment]
我不太记得具体怎么解决了，但是当时是mamba包版本不适配的问题，保证装的两个包版本适配就ok了



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 23, 2024 09:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MzeroMiko/VMamba] Expected u.is_cuda() to be true, but gotfalse. (Issue #43)




 
File "/home/LYH/anaconda3/envs/mamba/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 42, in forward
 out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)
 RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
 请问，怎么解决这个问题呀

**Comment by VagoLapis** [comment]
谢谢，问题已经解决了：）
